In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [23]:
arr=np.ones((5,5),dtype='int32')

In [24]:
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [25]:
b=np.zeros((3,3),dtype='int32')
b[1,1]=9
print(b)


[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [22]:
arr[1:4,1:4]=b
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 0 1]]
